name: CI

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux prerequisites
        run: ./scripts/setup-linux-prerequisites.sh

      - name: Build Ember
        run: ./scripts/install.sh release

      - name: Set up Python environment
        run: ./scripts/setup-python.sh

      - name: Run end-to-end tests
        run: ./scripts/run-e2e.sh --ember-cli "$HOME/.local/bin/ember-cli" --color never

      - name: Run unit tests
        run: ./bin/Release/ember_test
